import { Injectable } from '@nestjs/common';
import * as ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { Company } from '../companies/company.entity';

@Injectable()
export class ExportService {
  private flat(c: Company) {
    return {
      Name: c.name,
      CIN: c.cin || '',
      LLPIN: c.llpin || '',
      Website: c.website || '',
      Emails: (c.emails || []).join('; '),
      Phones: (c.phones || []).join('; '),
      Founders: (c.founders || []).join('; '),
      Address: c.address || '',
      Social: Object.entries(c.socialLinks || {}).map(([k, v]) => `${k}:${v}`).join('; '),
      StartupIndia: c.startupIndiaRecognised ? 'Yes' : 'No',
      DPIIT: c.dpiitNumber || '',
      Industry: c.industry || '',
      Stage: c.stage || '',
      MCAStatus: c.status || '',
      Sources: (c.sources || []).join('; '),
      Description: c.description || '',
    };
  }

  json(c: Company) {
    return Buffer.from(JSON.stringify(c, null, 2));
  }

  csv(c: Company) {
    return this.csvMany([c]);
  }

  // ---- multi-company (bulk) exports ----
  jsonMany(list: Company[]) {
    return Buffer.from(JSON.stringify(list.map((c) => this.flat(c)), null, 2));
  }

  csvMany(list: Company[]) {
    const rows = list.map((c) => this.flat(c));
    const headers = Object.keys(this.flat({} as Company));
    const esc = (v: any) => `"${String(v ?? '').replace(/"/g, '""')}"`;
    const lines = [
      headers.join(','),
      ...rows.map((r) => headers.map((h) => esc((r as any)[h])).join(',')),
    ];
    return Buffer.from(lines.join('\n'));
  }

  async excelMany(list: Company[]) {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Companies');
    const headers = Object.keys(this.flat({} as Company));
    ws.columns = headers.map((k) => ({ header: k, key: k, width: 24 }));
    list.forEach((c) => ws.addRow(this.flat(c)));
    ws.getRow(1).font = { bold: true };
    return Buffer.from(await wb.xlsx.writeBuffer());
  }

  pdfMany(list: Company[]): Promise<Buffer> {
    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (d) => chunks.push(d));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.fontSize(16).text(`Xchange Intel — ${list.length} companies`, { underline: true });
      doc.moveDown(0.5);
      list.forEach((c, i) => {
        doc.fontSize(12).fillColor('#1565c0').text(`${i + 1}. ${c.name}`);
        doc.fontSize(9).fillColor('#000');
        const row = this.flat(c);
        ['CIN', 'Industry', 'MCAStatus', 'Website', 'Emails', 'Phones', 'Address', 'DPIIT'].forEach((k) => {
          const v = (row as any)[k];
          if (v) doc.text(`${k}: ${v}`);
        });
        doc.moveDown(0.5);
        if (doc.y > 720) doc.addPage();
      });
      doc.end();
    });
  }

  async excel(c: Company) {
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet('Company');
    const row = this.flat(c);
    ws.columns = Object.keys(row).map((k) => ({ header: k, key: k, width: 28 }));
    ws.addRow(row);
    ws.getRow(1).font = { bold: true };
    return Buffer.from(await wb.xlsx.writeBuffer());
  }

  pdf(c: Company): Promise<Buffer> {
    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 40 });
      const chunks: Buffer[] = [];
      doc.on('data', (d) => chunks.push(d));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      doc.fontSize(20).text(c.name, { underline: true });
      doc.moveDown(0.5);
      if (c.aiOverview) doc.fontSize(10).fillColor('#444').text(c.aiOverview).moveDown(0.5);
      doc.fillColor('#000').fontSize(11);
      const row = this.flat(c);
      Object.entries(row).forEach(([k, v]) => {
        if (k === 'Description') return;
        doc.font('Helvetica-Bold').text(`${k}: `, { continued: true });
        doc.font('Helvetica').text(String(v) || '—');
      });
      doc.moveDown(0.5).fontSize(8).fillColor('#888')
        .text('Generated by Nexus Company Intelligence — public-data aggregation. Verify before use.');
      doc.end();
    });
  }
}
